# Generated by Django 4.2.2 on 2023-08-24 15:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusers",
            name="friend_requests_sent",
            field=models.ManyToManyField(
                blank=True,
                related_name="sent_friend_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customusers",
            name="play_requests_sent",
            field=models.ManyToManyField(
                blank=True,
                related_name="play_sent_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customusers",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name="customusers",
            name="friends",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="customusers",
            name="photo",
            field=models.ImageField(default="", upload_to="photos/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="customusers",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Никнейм может содержать только английские буквы, цифры, знаки "-" и "_"',
                        regex="^[a-zA-Z0-9_-]+$",
                    )
                ],
            ),
        ),
    ]
