# Generated by Django 4.2.2 on 2023-08-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customusers_friend_requests_sent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusers",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
