# Generated by Django 4.2.2 on 2023-08-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customusers_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customusers",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="customusers",
            unique_together={("username", "slug")},
        ),
    ]
