# Generated by Django 4.1.10 on 2023-11-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="games",
            name="score_first_user",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="games",
            name="score_second_user",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
